name: "Allocator Application"
description: "Application form for submitting a request to receive DataCap to distribute as an Allocator in the Filecoin Plus Program"
body:
- type: markdown
  attributes:
    value: |
      # Pathway Address Modification
      To apply to become an Allocator, please fill complete the following form.  Application turn around time is typically 5 business days. 
- type: input
  attributes:
    label: Email 
    description: The email for your Organization that you wish to setup for an Allocator
  validations:
    required: true
- type: input
  attributes:
    label: Github Handle  
    description: The Github handle(s) which will be authorized on the Allocator
  validations:
    required: true
- type: dropdown
  attributes:
    label: Which Pathway is this for? 
    options:
      - Open Data Pathway
      - Enterprise Private Data Pathway
      - Other
  validations:
    required: true
- type: input
  attributes:
    label: Data Owner Organization Name  
    description: Enter the Organization name which will represent and control this Allocator.
  validations:
    required: true
- type: dropdown
  attributes:
    label: Country or Region 
    options:
      - USA
      - Canada
      - China
  validations:
    required: true
- type: dropdown
  attributes:
    label: Allocator Industry Specialization
    options:
      - Agriculture 
      - Arts 
      - Construction
      - Education
      - Enviroment
      - Financial 
      - Government
      - HealthCare
      - IT & Technology
      - Media and Telecommunications
      - Not-for-Profit
      - Research 
      - Professional Services (Legal, consulting, advertising) 
      - Transportation
      - Utilities
      - Web3 or Crypto
      - Other
  validations:
    required: true
- type: input
  attributes:
    label: Organization Website 
    description: What is the website for your organization?  
  validations:
    required: false  
- type: input
  attributes:
    label: Social Media Handle  
    description:
  validations:
    required: true
- type: dropdown
  attributes:
    label: Social Media Type
    options:
      - Facebook
      - Slack
      - Twitter
      - WeChat
      - Other
  validations:
    required: true
- type: dropdown
  attributes:
    label: What is your role related to the dataset 
    options:
      - Data Owner
      - Data Preparer
      - Storage provider filling out application on behalf of the data owner
      - Data onramp entity that provides data onboarding services to multiple clients
      - Other
  validations:
    required: true
- type: input
  attributes:
    label: Total amount of DataCap being requested
    description:   
  validations:
    required: true
- type: input
  attributes:
    label: Expected size of single dataset (one copy)
    description:   
  validations:
    required: true
    
- type: dropdown
  attributes:
    label: Number of replicas to store
    options:
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - Other
  validations:
    required: true
